In [1]:
import zipfile

# Extract first dataset
with zipfile.ZipFile("archive.zip", "r") as zip_ref:
    zip_ref.extractall("amazon_dataset")

# Extract second dataset
with zipfile.ZipFile("archive (1).zip", "r") as zip_ref:
    zip_ref.extractall("electronics_dataset")

print("Datasets extracted successfully!")

Datasets extracted successfully!

In [2]:
import os

print("Amazon Dataset Files:")
print(os.listdir("amazon_dataset"))

print("\nElectronics Dataset Files:")
print(os.listdir("electronics_dataset"))

Amazon Dataset Files:
['electronics.csv']

Electronics Dataset Files:
['products.csv', 'reviews.csv']

In [3]:
# Import Required Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display all columns
pd.set_option("display.max_columns", None)

print("Libraries Imported Successfully!")

Libraries Imported Successfully!

In [4]:
# Load Datasets

electronics = pd.read_csv("amazon_dataset/electronics.csv")
products = pd.read_csv("electronics_dataset/products.csv")
reviews = pd.read_csv("electronics_dataset/reviews.csv")

print("Datasets Loaded Successfully!")

Datasets Loaded Successfully!

In [5]:
# Check Shape of Datasets

print("Electronics Dataset Shape :", electronics.shape)
print("Products Dataset Shape    :", products.shape)
print("Reviews Dataset Shape     :", reviews.shape)

Electronics Dataset Shape : (1292954, 10)
Products Dataset Shape    : (728, 34)
Reviews Dataset Shape     : (6327, 23)

In [6]:
print("Electronics Dataset")
display(electronics.head())

print("\nProducts Dataset")
display(products.head())

print("\nReviews Dataset")
display(reviews.head())

Electronics Dataset

,item_id,user_id,rating,timestamp,model_attr,category,brand,year,user_attr,split
0,0,0,5.0,1999-06-13,Female,Portable Audio & Video,NaN,1999,NaN,0
1,0,1,5.0,1999-06-14,Female,Portable Audio & Video,NaN,1999,NaN,0
2,0,2,3.0,1999-06-17,Female,Portable Audio & Video,NaN,1999,NaN,0
3,0,3,1.0,1999-07-01,Female,Portable Audio & Video,NaN,1999,NaN,0
4,0,4,2.0,1999-07-06,Female,Portable Audio & Video,NaN,1999,NaN,0

Products Dataset

,s.no,about_item,asin,availability,best_sellers_rank,brand_name,brand_page_url,breadcrumbs,customer_review_summary,default_variant/0,default_variant/1,default_variant/2,delivery_date,fastest_delivery_date,list_price,manufacturer,model_number,price_value,product_description,product_url,rating_count,rating_distribution/1star,rating_distribution/2star,rating_distribution/3star,rating_distribution/4star,rating_distribution/5star,rating_stars,recent_purchases,scrape_time,seller_name,seller_page_url,title,all_images,rank_1
0,0,Premium Comfort: Crafted from a high-quality c...,B0B59BJG6Y,In Stock,"#56,836 in Clothing, Shoes & Jewelry (See Top ...",MLYENX Store,https://www.amazon.com/stores/MLYENX/page/1FCD...,"Clothing, Shoes & Jewelry › Men › Clothing › A...",Customers find the shirts comfortable and well...,size:Large,"color:5 Pack Black, Dark Grey, Light Blue, Mil...",NaN,"Saturday, March 15","Tomorrow, March 11",List Price: $53.99,NaN,NaN,39.9926,NaN,https://www.amazon.com/dp/B0B59BJG6Y,"1,654 ratings",2%,1%,7%,15%,75%,4.6 out of 5 stars,50+ bought,03-10-2025 21:42,Greenfive,https://www.amazon.com/gp/help/seller/at-a-gla...,4/5 Pack Mens Polo Shirts Short Sleeve Quick D...,['https://m.media-amazon.com/images/I/41yUF65P...,85.0
1,1,Material: Men's polo shirt is made of soft pol...,B0DLGB4RYH,In Stock,"#50,261 in Clothing, Shoes & Jewelry (See Top ...",COOFANDY Store,https://www.amazon.com/stores/COOFANDY/page/23...,"Clothing, Shoes & Jewelry › Men › Clothing › S...",NaN,size:X-Large,color:Light Grey,NaN,"Saturday, March 15","Tomorrow, March 11",Typical price: $24.99,NaN,NaN,19.9920,NaN,https://www.amazon.com/dp/B0DLGB4RYH,20 ratings,0%,6%,11%,17%,66%,4.4 out of 5 stars,NaN,03-10-2025 21:42,COOFANDY,https://www.amazon.com/gp/help/seller/at-a-gla...,COOFANDY Men's Polo Shirts Short Sleeve Moistu...,['https://m.media-amazon.com/images/I/31a3mSs3...,199.0
2,2,"PERFORMANCE:These men polo shirts are soft,lig...",B0DRXF62JH,In Stock,"#69,641 in Clothing, Shoes & Jewelry (See Top ...",ZITY Store,https://www.amazon.com/stores/ZITY/page/F582B6...,"Clothing, Shoes & Jewelry › Men › Clothing › A...",NaN,size:X-Large,color:Bblack Grey Navy,NaN,"Saturday, March 15","Wednesday, March 12",List Price: $59.99,NaN,NaN,29.9950,NaN,https://www.amazon.com/dp/B0DRXF62JH,5 ratings,0%,0%,0%,37%,63%,4.6 out of 5 stars,NaN,03-10-2025 21:42,ZITY®,https://www.amazon.com/gp/help/seller/at-a-gla...,ZITY 3 Pack Men Polo Shirts Short Sleeve with ...,['https://m.media-amazon.com/images/I/41J5q-Ua...,111.0
3,3,【Material】: These golf shirts for men are made...,B0DK5FZ325,In Stock,"#194,649 in Clothing, Shoes & Jewelry (See Top...",Rouen Store,https://www.amazon.com/stores/ROUEN/page/4C407...,"Clothing, Shoes & Jewelry › Men › Clothing › A...",NaN,size:Small,color:Light Pink Stripe,NaN,"Saturday, March 15","Wednesday, March 12",NaN,NaN,NaN,32.9500,NaN,https://www.amazon.com/dp/B0DK5FZ325,22 ratings,0%,0%,0%,20%,80%,4.8 out of 5 stars,NaN,03-10-2025 21:43,MICHEL ROUEN,https://www.amazon.com/gp/help/seller/at-a-gla...,Rouen Mens Golf Shirt Moisture Wicking Dry Fit...,['https://m.media-amazon.com/images/I/31J1ttvf...,266.0
4,4,MOISTURE WICKING: The fabric of the summer gol...,B0BGXTC1FR,In Stock,"#3,664 in Clothing, Shoes & Jewelry (See Top 1...",V VALANCH Store,https://www.amazon.com/stores/VVALANCH/page/0E...,"Clothing, Shoes & Jewelry › Men › Clothing › A...",Customers find the shirt has a good fit and lo...,size:X-Large,color:A-moonblue,NaN,"Saturday, March 15","Tomorrow, March 11",List Price: $38.99,NaN,NaN,26.9931,NaN,https://www.amazon.com/dp/B0BGXTC1FR,"2,175 ratings",5%,2%,7%,17%,69%,4.4 out of 5 stars,NaN,03-10-2025 21:43,Zhengdaqian,https://www.amazon.com/gp/help/seller/at-a-gla...,V VALANCH Mens Polo Shirts Short Sleeve Moistu...,['https://m.media-amazon.com/images/I/31Ff+3Ib...,11.0

Reviews Dataset

,s.no,helpfulVoteCount,images/0,images/1,images/2,images/3,images/4,images/5,images/6,images/7,productASIN,productVariant,rating,reviewID,reviewMetadata,reviewPosition,reviewText,reviewTitle,reviewURL,verifiedPurchase,videos/0,cleaned_review_text,sentiment_score
0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B0DLGB4RYH,Color: BlackSize: X-Large,5.0,R2AUQFPJY5ERCZ,"Reviewed in the United States on March 6, 2025",1,‚úçÔ∏è The COOFANDY Men's Polo Shirt is a fant...,Stylish and Lightweight COOFANDY Polo Shirt,https://www.amazon.com/review/R2AUQFPJY5ERCZ,False,NaN,coofandy men polo shirt fantastic blend style ...,0.292024
1,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B0DRXF62JH,Color: Bblack Grey NavySize: 3X-Large,5.0,R1YNLJ0QFLB1VT,"Reviewed in the United States on March 7, 2025",1,I love these. They look good. They fit well. T...,New favorite shirts,https://www.amazon.com/review/R1YNLJ0QFLB1VT,False,NaN,love look good fit well comfortable breathable...,0.560000
2,2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B0DRXF62JH,Color: Grey Navy DuckblueSize: Medium,4.0,R11LIYW9RMDK9R,"Reviewed in the United States on February 27, ...",2,My expectations were low -- how good could shi...,Incredibly Good Deal,https://www.amazon.com/review/R11LIYW9RMDK9R,False,NaN,expectation low good could shirt sell one mist...,0.192321
3,3,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B0DRXF62JH,Color: Black Duckblue WineredSize: X-Large,5.0,R3K9X391DJNTPZ,"Reviewed in the United States on February 26, ...",3,This 3-pack of multi-color shirts is really a ...,Higher quality & breathable 3-pack shirt set t...,https://www.amazon.com/review/R3K9X391DJNTPZ,False,NaN,pack multicolor shirt really brainer wear type...,0.307949
4,4,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B0DRXF62JH,Color: Bblack Grey NavySize: X-Large,5.0,RP17IW9ZKENDZ,"Reviewed in the United States on February 20, ...",4,With these three polo shirts I was very satisf...,Pocket Polos Looks Good,https://www.amazon.com/review/RP17IW9ZKENDZ,False,NaN,three polo shirt satisfied quality material go...,0.250000

In [7]:
print("Electronics Dataset Information")
electronics.info()

print("\nProducts Dataset Information")
products.info()

print("\nReviews Dataset Information")
reviews.info()

Electronics Dataset Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1292954 entries, 0 to 1292953
Data columns (total 10 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   item_id     1292954 non-null  int64
 1   user_id     1292954 non-null  int64
 2   rating      1292954 non-null  float64
 3   timestamp   1292954 non-null  object
 4   model_attr  1292954 non-null  object
 5   category    1292954 non-null  object
 6   brand       331120 non-null   object
 7   year        1292954 non-null  int64
 8   user_attr   174124 non-null   object
 9   split       1292954 non-null  int64
dtypes: float64(1), int64(4), object(5)
memory usage: 98.6+ MB

Products Dataset Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 728 entries, 0 to 727
Data columns (total 34 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   s.no                       728 non-null    int64
 1   about_item                 728 non-null    object
 2   asin                       728 non-null    object
 3   availability               715 non-null    object
 4   best_sellers_rank          558 non-null    object
 5   brand_name                 728 non-null    object
 6   brand_page_url             649 non-null    object
 7   breadcrumbs                715 non-null    object
 8   customer_review_summary    634 non-null    object
 9   default_variant/0          696 non-null    object
 10  default_variant/1          658 non-null    object
 11  default_variant/2          1 non-null      object
 12  delivery_date              702 non-null    object
 13  fastest_delivery_date      667 non-null    object
 14  list_price                 401 non-null    object
 15  manufacturer               266 non-null    object
 16  model_number               199 non-null    object
 17  price_value                707 non-null    float64
 18  product_description        271 non-null    object
 19  product_url                728 non-null    object
 20  rating_count               719 non-null    object
 21  rating_distribution/1star  728 non-null    object
 22  rating_distribution/2star  728 non-null    object
 23  rating_distribution/3star  728 non-null    object
 24  rating_distribution/4star  728 non-null    object
 25  rating_distribution/5star  728 non-null    object
 26  rating_stars               719 non-null    object
 27  recent_purchases           569 non-null    object
 28  scrape_time                728 non-null    object
 29  seller_name                707 non-null    object
 30  seller_page_url            426 non-null    object
 31  title                      728 non-null    object
 32  all_images                 728 non-null    object
 33  rank_1                     540 non-null    float64
dtypes: float64(2), int64(1), object(31)
memory usage: 193.5+ KB

Reviews Dataset Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6327 entries, 0 to 6326
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   s.no                 6327 non-null   int64
 1   helpfulVoteCount     6327 non-null   int64
 2   images/0             516 non-null    object
 3   images/1             212 non-null    object
 4   images/2             98 non-null     object
 5   images/3             49 non-null     object
 6   images/4             26 non-null     object
 7   images/5             14 non-null     object
 8   images/6             7 non-null      object
 9   images/7             5 non-null      object
 10  productASIN          6327 non-null   object
 11  productVariant       5836 non-null   object
 12  rating               6320 non-null   float64
 13  reviewID             6327 non-null   object
 14  reviewMetadata       6296 non-null   object
 15  reviewPosition       6327 non-null   int64
 16  reviewText           6289 non-null   object
 17  reviewTitle          6313 non-null   object
 18  reviewURL            6327 non-null   object
 19  verifiedPurchase     6327 non-null   bool
 20  videos/0             34 non-null     object
 21  cleaned_review_text  6288 non-null   object
 22  sentiment_score      6327 non-null   float64
dtypes: bool(1), float64(2), int64(3), object(17)
memory usage: 1.1+ MB

In [8]:
print("Missing Values in Electronics Dataset")
print(electronics.isnull().sum())

print("\nMissing Values in Products Dataset")
print(products.isnull().sum())

print("\nMissing Values in Reviews Dataset")
print(reviews.isnull().sum())

Missing Values in Electronics Dataset
item_id             0
user_id             0
rating              0
timestamp           0
model_attr          0
category            0
brand          961834
year                0
user_attr     1118830
split               0
dtype: int64

Missing Values in Products Dataset
s.no                           0
about_item                     0
asin                           0
availability                  13
best_sellers_rank            170
brand_name                     0
brand_page_url                79
breadcrumbs                   13
customer_review_summary       94
default_variant/0             32
default_variant/1             70
default_variant/2            727
delivery_date                 26
fastest_delivery_date         61
list_price                   327
manufacturer                 462
model_number                 529
price_value                   21
product_description          457
product_url                    0
rating_count                   9
rating_distribution/1star      0
rating_distribution/2star      0
rating_distribution/3star      0
rating_distribution/4star      0
rating_distribution/5star      0
rating_stars                   9
recent_purchases             159
scrape_time                    0
seller_name                   21
seller_page_url              302
title                          0
all_images                     0
rank_1                       188
dtype: int64

Missing Values in Reviews Dataset
s.no                      0
helpfulVoteCount          0
images/0               5811
images/1               6115
images/2               6229
images/3               6278
images/4               6301
images/5               6313
images/6               6320
images/7               6322
productASIN               0
productVariant          491
rating                    7
reviewID                  0
reviewMetadata           31
reviewPosition            0
reviewText               38
reviewTitle              14
reviewURL                 0
verifiedPurchase          0
videos/0               6293
cleaned_review_text      39
sentiment_score           0
dtype: int64

In [9]:
# Missing Values Percentage

print("Products Dataset Missing Values (%)")
missing_products = (products.isnull().sum()/len(products))*100
print(missing_products.sort_values(ascending=False))

print("\nReviews Dataset Missing Values (%)")
missing_reviews = (reviews.isnull().sum()/len(reviews))*100
print(missing_reviews.sort_values(ascending=False))

print("\nElectronics Dataset Missing Values (%)")
missing_electronics = (electronics.isnull().sum()/len(electronics))*100
print(missing_electronics.sort_values(ascending=False))

Products Dataset Missing Values (%)
default_variant/2            99.862637
model_number                 72.664835
manufacturer                 63.461538
product_description          62.774725
list_price                   44.917582
seller_page_url              41.483516
rank_1                       25.824176
best_sellers_rank            23.351648
recent_purchases             21.840659
customer_review_summary      12.912088
brand_page_url               10.851648
default_variant/1             9.615385
fastest_delivery_date         8.379121
default_variant/0             4.395604
delivery_date                 3.571429
seller_name                   2.884615
price_value                   2.884615
availability                  1.785714
breadcrumbs                   1.785714
rating_count                  1.236264
rating_stars                  1.236264
about_item                    0.000000
brand_name                    0.000000
all_images                    0.000000
title                         0.000000
asin                          0.000000
scrape_time                   0.000000
rating_distribution/5star     0.000000
rating_distribution/4star     0.000000
rating_distribution/3star     0.000000
rating_distribution/2star     0.000000
rating_distribution/1star     0.000000
product_url                   0.000000
s.no                          0.000000
dtype: float64

Reviews Dataset Missing Values (%)
images/7               99.920974
images/6               99.889363
images/5               99.778726
images/4               99.589063
videos/0               99.462621
images/3               99.225541
images/2               98.451083
images/1               96.649281
images/0               91.844476
productVariant          7.760392
cleaned_review_text     0.616406
reviewText              0.600601
reviewMetadata          0.489964
reviewTitle             0.221274
rating                  0.110637
verifiedPurchase        0.000000
reviewURL               0.000000
s.no                    0.000000
reviewPosition          0.000000
reviewID                0.000000
helpfulVoteCount        0.000000
productASIN             0.000000
sentiment_score         0.000000
dtype: float64

Electronics Dataset Missing Values (%)
user_attr     86.532854
brand         74.390427
item_id        0.000000
user_id        0.000000
rating         0.000000
timestamp      0.000000
model_attr     0.000000
category       0.000000
year           0.000000
split          0.000000
dtype: float64

In [10]:
# Check Duplicate Records

print("Duplicate Rows in Products :", products.duplicated().sum())
print("Duplicate Rows in Reviews :", reviews.duplicated().sum())
print("Duplicate Rows in Electronics :", electronics.duplicated().sum())

Duplicate Rows in Products : 0
Duplicate Rows in Reviews : 0
Duplicate Rows in Electronics : 0

In [11]:
# Remove Duplicate Records

products.drop_duplicates(inplace=True)
reviews.drop_duplicates(inplace=True)
electronics.drop_duplicates(inplace=True)

print("Duplicates Removed Successfully!")

Duplicates Removed Successfully!

In [12]:
print(products.shape)
print(reviews.shape)
print(electronics.shape)

(728, 34)
(6327, 23)
(1292954, 10)

In [23]:
products["rating_stars"] = products["rating_stars"].fillna(
    products["rating_stars"].median()
)

In [17]:
products["rating_stars"].head()

0    4.6
1    4.4
2    4.6
3    4.8
4    4.4
Name: rating_stars, dtype: float64

In [18]:
products["rating_stars"].dtype

dtype('float64')

In [24]:
products["rating_count"].head(10)

0     1,654 ratings
1        20 ratings
2         5 ratings
3        22 ratings
4     2,175 ratings
5    11,355 ratings
6    13,349 ratings
7     3,781 ratings
8     2,581 ratings
9     1,215 ratings
Name: rating_count, dtype: object

In [25]:
products["price_value"].head(10)

0    39.9926
1    19.9920
2    29.9950
3    32.9500
4    26.9931
5    49.5000
6    49.5000
7    42.9970
8    49.5000
9    48.9900
Name: price_value, dtype: float64

In [26]:
products[["price_value", "rating_count"]].dtypes

price_value     float64
rating_count     object
dtype: object

In [28]:
products["rating_count"].head(10)

0     1,654 ratings
1        20 ratings
2         5 ratings
3        22 ratings
4     2,175 ratings
5    11,355 ratings
6    13,349 ratings
7     3,781 ratings
8     2,581 ratings
9     1,215 ratings
Name: rating_count, dtype: object

In [29]:
products["rating_count"] = (
    products["rating_count"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.replace("ratings", "", regex=False)
    .str.replace("rating", "", regex=False)
    .str.strip()
)

products["rating_count"] = pd.to_numeric(
    products["rating_count"],
    errors="coerce"
)

products["rating_count"] = products["rating_count"].fillna(0).astype(int)

dtype('int64')

In [31]:
import os

# Create processed folder if it doesn't exist
os.makedirs("processed", exist_ok=True)

# Save cleaned datasets
products.to_csv("processed/products_clean.csv", index=False)
reviews.to_csv("processed/reviews_clean.csv", index=False)
electronics.to_csv("processed/electronics_clean.csv", index=False)

print("✅ Cleaned datasets saved successfully!")

✅ Cleaned datasets saved successfully!